// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },

  // The OfferGuide schema shares its database with the portal's original
  // tables, which predate Prisma and are still managed by raw mysql2 queries.
  // Without declaring them, `prisma migrate dev` sees tables it has no
  // migration for, reports "Drift detected", and offers to reset the database
  // — which would drop the portal's real data. Listing them here tells Prisma
  // they are not its business: it will neither migrate nor diff them.
  //
  // SPRINT 9 modelled `sanjeedausers` as the read-only UserInfo model, and it
  // STAYS external. Being external is what makes the model safe: it can be read
  // through Prisma while Prisma stays out of its DDL.
  //
  // Verified, do not undo: with `sanjeedausers` off this list,
  // `prisma migrate diff` proposes
  //     ALTER TABLE `sanjeedausers` DROP COLUMN `google_id`, DROP COLUMN `password`,
  //       DROP COLUMN `reset_code`, DROP COLUMN `reset_code_expiry`, …
  // plus dropping four email indexes — because UserInfo deliberately models only
  // the columns permission checks need. A `migrate dev` run in that state would
  // destroy the portal's credentials. The `role` column is therefore added by
  // scripts/migrate-roles.mjs, not by a Prisma migration.
  experimental: {
    externalTables: true,
  },
  tables: {
    external: ["users", "sanjeedausers", "forgot_password"],
  },
});
