// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },

  // The OfferGuide schema shares its database with the portal's original
  // tables, which predate Prisma and are still managed by raw mysql2 queries.
  // Without declaring them, `prisma migrate dev` sees tables it has no
  // migration for, reports "Drift detected", and offers to reset the database
  // — which would drop the portal's real data. Listing them here tells Prisma
  // they are not its business: it will neither migrate nor diff them.
  experimental: {
    externalTables: true,
  },
  tables: {
    external: ["users", "sanjeedausers", "forgot_password"],
  },
});
